# Generated by Django 6.0.7 on 2026-07-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ats_platform', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('ats_platform', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='tracker.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('comp', models.CharField(blank=True, max_length=100)),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.posting')),
            ],
        ),
    ]
