# Generated by Django 6.0.7 on 2026-07-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='comp',
        ),
        migrations.AddField(
            model_name='application',
            name='avg_comp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='lowest_comp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='avg_comp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='lowest_comp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
