# Generated by Django 6.0.7 on 2026-07-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_application_comp_application_avg_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
