# Generated by Django 6.0.7 on 2026-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='workplace_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
