# Generated by Django 6.0.7 on 2026-07-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_posting_posted_at_posting_workplace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
