# Generated by Django 6.0.7 on 2026-08-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_company_is_invalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'unique_together': {('city', 'state', 'country')},
            },
        ),
        migrations.AddField(
            model_name='posting',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='postings', to='tracker.location'),
        ),
    ]
