# Generated by Django 6.0.7 on 2026-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_location_posting_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gen_info',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
