# Generated by Django 6.0.7 on 2026-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_company_gen_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_us_engineering_posting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='preference_rank',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('us', 'US'), ('europe', 'Europe'), ('other', 'Other'), ('remote', 'Remote'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
