# Generated by Django 6.0.7 on 2026-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_company_last_us_engineering_posting_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='ats_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='fit_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='posting',
            name='recruiter_fit_score',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
