# Generated by Django 6.0.7 on 2026-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_posting_ats_score_posting_fit_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ats_scoring_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
