# Generated by Django 6.0.7 on 2026-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_company_ats_scoring_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='role_type',
            field=models.CharField(blank=True, choices=[('software', 'Software'), ('hardware', 'Hardware/Physical'), ('hybrid', 'Hybrid'), ('other', 'Other/Non-Engineering')], default='', max_length=20),
        ),
    ]
