# Generated by Django 6.0.7 on 2026-08-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_posting_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('technical', 'Technical'), ('system_design', 'System Design'), ('onsite', 'Onsite')], max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_stages', to='tracker.application')),
            ],
        ),
    ]
