# Generated by Django 6.0.7 on 2026-08-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_interviewstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstage',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
